import {
  NonprofitProfile,
  GrantOpportunity,
  ChatMessage,
  TimelineItem,
} from './types';

export const mockProfile: NonprofitProfile = {
  id: 'org-123',
  name: 'Ocean Rescue Init',
  mission: 'To protect marine ecosystems through community-led conservation and data-driven research.',
  location: 'Monterey, CA',
  focusAreas: ['Marine Conservation', 'Climate Action', 'Community Education'],
  annualBudget: '$1,200,000',
  nonprofitStatus: '501(c)(3)',
  summary: 'Founded in 2015, Ocean Rescue Init has protected over 500 miles of coastline and educated 20,000 students on ocean health.',
};

export const mockGrants: GrantOpportunity[] = [
  {
    id: 'g-001',
    title: 'Coastal Resilience Innovation Fund',
    funder: 'Blue Planet Foundation',
    deadline: '2026-05-15',
    fundingAmount: '$250,000',
    matchScore: 95,
    summary: 'A grant supporting highly scalable, community-driven coastal resilience projects.',
    eligibility: 'Must be a 501(c)(3) based in California with an annual budget under $5M.',
    strengths: ['Perfect alignment with mission', 'Requires community-led approach'],
    risks: ['High competition', 'Complex reporting requirements'],
    sourceUrl: 'https://example.com/grant',
    status: 'open',
  },
  {
    id: 'g-002',
    title: 'Marine Data Science Grant',
    funder: 'Tech For Oceans',
    deadline: '2026-06-01',
    fundingAmount: '$100,000',
    matchScore: 88,
    summary: 'Seed funding for technology-focused marine conservation projects.',
    eligibility: 'Open to nonprofits collaborating with local universities on data pipelines.',
    strengths: ['Requires data-driven research', 'Flexible usage of funds'],
    risks: ['Tight deadline'],
    sourceUrl: 'https://example.com/grant',
    status: 'open',
  },
  {
    id: 'g-003',
    title: 'Youth Climate Action Fellowship',
    funder: 'Green Future Trust',
    deadline: '2026-08-10',
    fundingAmount: '$50,000',
    matchScore: 75,
    summary: 'Fellowships for organizations prioritizing youth education in climate sectors.',
    eligibility: 'Must demonstrate past success in youth outreach programs.',
    strengths: ['Aligns with Community Education focus'],
    risks: ['Lower funding amount compared to our core programs'],
    sourceUrl: 'https://example.com/grant',
    status: 'open',
  },
  {
    id: 'g-004',
    title: 'Global Ocean Cleanup Init',
    funder: 'International Maritime Org',
    deadline: '2026-04-01',
    fundingAmount: '$1,000,000',
    matchScore: 65,
    summary: 'Massive infrastructure grants for large-scale ocean cleanups.',
    eligibility: 'Open to international organizations with budgets over $5M.',
    strengths: ['Huge funding potential'],
    risks: ['Eligibility gap: budget too small', 'Location constraint'],
    sourceUrl: 'https://example.com/grant',
    status: 'upcoming',
  },
  {
    id: 'g-005',
    title: 'Monterey Bay Restoration Grant',
    funder: 'California Wildlife Board',
    deadline: '2026-04-30',
    fundingAmount: '$150,000',
    matchScore: 98,
    summary: 'Targeted funding for immediate restoration activities in the Monterey Bay area.',
    eligibility: 'Local nonprofits active in Monterey Bay with immediate conservation goals.',
    strengths: ['Perfect location match', 'Immediate funding', 'Aligns closely with current projects', 'Strong relationships with funder'],
    risks: ['Short implementation timeline'],
    sourceUrl: 'https://example.com/grant',
    status: 'open',
  },
  {
    id: 'g-006',
    title: 'SustainTheSea Capacity Building',
    funder: 'Oceanic Institute',
    deadline: '2026-09-01',
    fundingAmount: '$75,000',
    matchScore: 82,
    summary: 'Unrestricted grants intended to build organizational capacity, such as upgrading CRM or data systems.',
    eligibility: '501(c)(3) organizations operating in coastal regions.',
    strengths: ['Unrestricted funds', 'Low barrier to entry'],
    risks: [],
    sourceUrl: 'https://example.com/grant',
    status: 'open',
  },
];

export const mockTimeline: TimelineItem[] = [
  {
    id: 't-1',
    title: 'Review eligibility thoroughly',
    dueDate: '2026-04-01',
    status: 'complete',
    description: 'Ensure our 501(c)(3) and budget data meets their criteria.',
  },
  {
    id: 't-2',
    title: 'Collect Letters of Support',
    dueDate: '2026-04-15',
    status: 'in progress',
    description: 'Reach out to local university partners and community leaders.',
  },
  {
    id: 't-3',
    title: 'Finalize Project Budget',
    dueDate: '2026-04-20',
    status: 'upcoming',
    description: 'Create line-item budget aligning with the proposed activities.',
  },
  {
    id: 't-4',
    title: 'Submit Proposal Draft',
    dueDate: '2026-04-25',
    status: 'upcoming',
    description: 'Submit to portal for final review by the board.',
  },
  {
    id: 't-5',
    title: 'Application Deadline',
    dueDate: '2026-04-30',
    status: 'upcoming',
    description: 'Final deadline to submit all materials to the funder.',
  },
];

export const mockChats: ChatMessage[] = [
  {
    id: 'msg-1',
    role: 'user',
    content: 'Can you help me find grants for marine conservation in California?',
    timestamp: '10:00 AM',
  },
  {
    id: 'msg-2',
    role: 'agent',
    content: "I found 3 strong matches for marine conservation in California. The most promising one is the **Coastal Resilience Innovation Fund** ($250,000) from the Blue Planet Foundation. Your match score is 95 because it aligns perfectly with your community-led approach. Would you like to review its eligibility criteria?",
    timestamp: '10:00 AM',
    sources: [
      {
        id: 'src-1',
        title: 'Grant Opportunity: Coastal Resilience',
        snippet: 'Must be a 501(c)(3) based in California with an annual budget under $5M.',
        type: 'opportunity',
      },
      {
        id: 'src-2',
        title: 'Profile Document: Mission Statement',
        snippet: 'To protect marine ecosystems through community-led conservation...',
        type: 'internal_doc',
      }
    ],
  },
];
